insert into division_academica (nombre_division_academica) values
("División Académica de Tecnologías de la Información y Diseño"),
("División Académica de Mecánica Industrial"),
("División Académica Económica-Administrativa"),
("División Académica de Terapia Física");

insert into carrera (nombre_carrera, division_academica_id_division_academica) values
('TSU Mantenimiento: área industrial', 2),
('ingeniería en Mantenimiento Industrial', 2),
('TSU Mecatrónica: área automatización', 2),
('ingeniería en Mecatrónica', 2),
('TSU Procesos industriales: área manufactura', 2),
'ingeniería Industrial', 2),
('TSU Nanotecnología: área materiales', 2),
('ingeniería en Nanotecnología', 2),
('TSU Diseño y moda industrial: área producción', 1),
('ingeniería en Diseño Textil y Moda', 1),
('TSU Tecnologías de la información: área desarrollo de software multiplataforma', 1),
('ingeniería en Desarrollo y Gestión de Software', 1),
('TSU Diseño digital: área animación', 1),
('Licenciatura en Diseño Digital', 1),
('TSU Tecnologías de la Información: área infraestructura de redes digitales', 1),
('Ingeniería en Redes Inteligentes y Ciberseguridad', 1),
('TSU Desarrollo de negocios: área mercadotecnia', 3),
('Licenciatura en Innovación de Negocios y Mercadotecnia', 3),
('TSU Administración: área capital humano', 3),
('Licenciatura en Gestión de Capital Humano', 3),
('TSU Turismo de salud y bienestar', 4),
('TSU Terapia física: área rehabilitación', 4),
(' Licenciatura en Terapia Física', 4);

insert into usuario (nombre_usuario, apellido_usuario, correo_electronico, contrasena, codigo, fecha_registrado, id_tipo_usuario) values
('Diego Ricardo', 'Amador Casillas', '20233tn077@utez.edu.mx', sha2('20233tn077', 256), null, now(), 1),
('Elias Manuel', 'Marquez Bailón', '20233tn068@utez.edu.mx', sha2('20233tn068', 256), null, now(),3),
('Erik', 'Balmaceda Miranda', '20223tn044@utez.edu.mx', sha2('20223tn044', 256), null, now(), 3),
('Jesus Emmanuel', 'Galvez Osorio', '20233tn108@utez.edu.mx', sha2('20233tn108', 256), null, now(), 3),
('Paula', 'Vargas Ledesma', '20233tn071@utez.edu.mx', sha2('20233tn071', 256), null, now(), 3),
('Piero Leonardo', 'Vargas Ledesma', '20233tn072@utez.edu.mx', sha2('20233tn072', 256), null, now(), 3),
('Hugo Daniel', 'Castillo García', '20233tn991@utez.edu.mx', sha2('20233tn991', 256), null, now(), 3),
('Ángel', 'Sotelo Fuentes', '20233tn992@utez.edu.mx', sha2('20233tn992', 256), null, now(), 3),
('Raúl Alejandro', 'Sánchez Jimenez', '20233tn993@utez.edu.mx', sha2('20233tn993', 256), null, now(), 3),
('Sebastian', 'Pedroza Aguilar', '20233tn994@utez.edu.mx', sha2('20233tn994', 256), null, now(), 3),
('Eduardo', 'Ramirez Peña', '20233tn995@utez.edu.mx', sha2('20233tn995', 256), null, now(), 3),
('Monse', 'Juarez Espinosa', '20233tn996@utez.edu.mx', sha2('20233tn996', 256), null, now(), 2),
('Paola', 'Ocampo Bustamante', '20233tn997@utez.edu.mx', sha2('20233tn997', 256), null, now(), 4),
('Blanca', 'Casillas Arias', '20233tn998@utez.edu.mx', sha2('20233tn998', 256), null, now(), 3);

insert into periodo (descripcion, fecha_inicio, fecha_final) values
('cuatrimestre enero-abril 2024', '2024-01-04', '2024-04-26'),
('cuatrimestre mayo-agosto 2024', '2024-04-29', '2024-08-30'),
('cuatrimestre septiembre-diciembre 2024', '2024-09-02','2024-12-20');

insert into grupo (grado, grupo, periodo_id_periodo) values
(3, 'A', 2),
(3, 'B', 2),
(3, 'C', 2),
(3, 'D', 2),
(3, 'E', 2),
(3, 'F', 2),
(3, 'G', 2),
(3, 'H', 2),
(9, 'A', 2),
(9, 'B', 2),
(9, 'C', 2),
(9, 'D', 2),
(9, 'E', 2);

insert into usuario_tiene_grupo values
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(2, 7),
(2, 8),
(2, 9),
(2, 10),
(2, 11),
(2, 14);

insert into grupo_tiene_carrera values
(11,1),
(11,2);

insert into examen (nombre_examen, cantidad_preguntas, estado, descripcion) values ('Examen teorico U3 Sistemas operativos 3-A-DSM', 15, 1, 'Buen dia. Por favor contestar. Saludos cordiales.');

insert into usuario_tiene_examen values (12, 1);

insert into aplicacion (periodo_id_periodo, examen_id_examen) values (2, 1);

insert into pregunta (pregunta, id_tipo_pregunta) values
('¿Cual es el comando para ver el calendario?', 2),
('¿Cual es el comando que nos permite movernos entre directorios?', 2),
('¿Con que comando se crea un directorio?', 2),
('¿Que comando nos permite ver los archicvos de un directorio?', 2),
('¿Que comando nos permite crear un archivo?',2),
('En caso de querer ver los archivos del directorio en que nos encontramos, ordenados por tamaño, ¿que comando deberiamos de usar?', 2),
('En caso de querer movernos al directorio raiz del sistema, ¿que comando deberiamos de usar', 2),
('En caso de haber creado un archivo prueba.txt, ¿que comando deberiamos de usar para eliminarlo?', 2),
('En caso de querer ver los archivos y carpetas del directorio en el que nos encontramos con toda su informacion, ¿que comando se deberia de usar?', 2),
('En caso de querer ver las ultimas 15 lineas de un archivo llamado texto.txt, ¿que comando deberiamos de usar?', 2),
('¿Cuales son los dos editores de texto en Ubuntu Server?', 2),
('¿Para que nos sirve un editor de texto en Ubuntu Server?', 2),
('¿Cual es la funcion del comando sudo?', 2),
('¿Cual es la funcion del comando man?', 2),
('¿Cual es la funcion del comando clear?', 2),
('¿Qué es un sistema operativo?', 1),
('Cuál es su función principal?', 1),
('¿Cuáles son las diferencias entre sistemas operativos de escritorio (como Windows o macOS) y sistemas operativos móviles (como Android o iOS)?', 1),
('¿Cómo se maneja la administración de procesos en un sistema operativo?', 1),
('¿Qué es un kernel y cuál es su papel en un sistema operativo?', 1),
('¿Cuáles son los principales sistemas de archivos utilizados en sistemas operativos?', 1),
('¿Qué es la memoria virtual y cómo se gestiona en un sistema operativo?', 1),
('¿Cuál es la importancia de los controladores (drivers) en un sistema operativo?', 1),
'¿Qué es la concurrencia y cómo se maneja en sistemas operativos multitarea?', 1),
('¿Cuáles son los desafíos de seguridad que enfrentan los sistemas operativos?', 1),
('¿Cómo se realiza la planificación de CPU en un sistema operativo?', 1),
('¿Qué es la paginación y cómo se implementa en un sistema operativo?', 1),
('¿Cuál es la diferencia entre un sistema operativo monolítico y uno basado en microkernel?', 1),
('¿Cómo se maneja la concurrencia en sistemas operativos distribuidos?', 1),
('¿Qué son los procesos en segundo plano (background processes) y cómo afectan el rendimiento del sistema?', 1);

insert into examen_tiene_pregunta values (1,1), (1,2), (1,3), (1,4), (1,5), (1,6), (1,7), (1,8), (1,9), (1,10), (1,11), (1,12), (1,13), (1,14), (1,15);

insert into opcion (opcion) values
('calendar'),
('cal'),
('date'),
('cd'),
('move'),
'esc'),
('create'),
('mkdir'),
('crtdir'),
('ls'),
('view'),
('dir'),
('mkfile'),
('touch'),
('crt'),
('ls -h'),
('ls -r'),
('ls -t'),
('cd root'),
('cd $'),
('cd /'),
('del prueba.txt'),
('rm prueba.txt'),
('prueba.txt -r'),
('ls -l'),
('ls -R'),
('ls -ZZ'),
('tail tex'),
('last texto.txt'),
('head texto.txt'),
('db y cl'),
('rim y tx'),
('vi y nano'),
('Permiten a los usuarios crear y modificar archivos de texto, como archivos de configuración y scripts de automatización.'),
('Sirven para ejecutar programas de gráficos intensivos y videojuegos en el servidor.'),
('Permiten la edición de archivos de texto únicamente a través de interfaces gráficas avanzadas.'),
('Sirve para cambiar el idioma del sistema operativo sin necesidad de reiniciar el servidor.'),
('Permite a los usuarios ejecutar comandos con privilegios administrativos, otorgando permisos temporales para realizar tareas que normalmente requieren acceso de superusuario.'),
('Permite la ejecución de programas exclusivamente en modo de usuario, sin ningún privilegio adicional.'),
('Sirve para desinstalar programas y paquetes del sistema de manera permanente.'),
('Se utiliza para ejecutar scripts de automatización sin necesidad de permisos adicionales.'),
('Proporciona el manual de usuario de otros comandos y programas del sistema, detallando su uso, opciones y ejemplos.'),
('Sirve para reiniciar el servidor de manera segura y ráp'),
('Permite realizar copias de seguridad automáticas de todos los archivos del sistema.'),
('Se utiliza para limpiar la pantalla del terminal, eliminando todo el texto visible y dejando una pantalla en blanco.');

insert into pregunta_opcion (pregunta_id_pregunta, opcion_id_opcion, correcta) values
(1,1,0),
(1,2,1),
(1,3,0),
(2,4,1),
(2,5,0),
(2,6,0),
(3,7,0),
(3,8,1),
(3,9,0),
(4,10,1),
(4,11,0),
(4,12,0),
(5,13,0),
(5,14,1),
(5,15,0),
(6,16,1),
(6,17,0),
(6,18,0),
(7,19,0),
(7,20,0),
(7,21,1),
(8,22,0),
(8,23,1),
(8,24,0),
(9,25,1),
(9,26,0),
(9,27,0),
(10,28,1),
(10,29,0),
(10,30,0),
(11,31,0),
(11,32,0),
(11,33,1),
(12,34,1),
(12,35,0),
(12,36,0),
(13,37,0),
(13,38,1),
(13,39,0),
(14,40,0),
(14,41,0),
(14,42,1),
(15,43,0),
(15,44,0),
(15,45,1);

insert into calificacion (calificacion, usuario_id_usuario, aplicacion_id_aplicacion) values (10, 2, 1);

insert into respuesta_opcion (pregunta_opcion_pregunta_id_pregunta, pregunta_opcion_opcion_id_opcion, aplicacion_id_aplicacion) values
(1, 2, 1),
(2, 4, 1),
(3, 8, 1),
(4, 10, 1),
(5, 14, 1),
(6, 16, 1),
(7, 21, 1),
(8, 23, 1),
(9, 25, 1),
(10, 28, 1),
(11, 33, 1),
(12, 34, 1),
(13, 38, 1),
(14, 41, 1),
(15, 44, 1);

insert into respuesta_abierta (pregunta_id_pregunta, aplicacion_id_aplicacion, respuesta, correcta) values
(16, 1, 'software que actúa como intermediario entre el hardware de una computadora y las aplicaciones que se ejecutan en ella.', 0),
(17, 1, 'administrar recursos (como memoria, CPU y dispositivos) y proporcionar una interfaz para que los usuarios interactúen con la máquina.', 0),
(18, 1, 'Los sistemas operativos de escritorio están diseñados para computadoras personales, mientras que los sistemas operativos móviles se utilizan en dispositivos móviles como teléfonos y tabletas.', 0),
(19, 1, 'La administración de procesos implica la creación, planificación y finalización de tareas en ejecución. El sistema operativo asigna recursos y decide qué proceso se ejecuta en cada momento.', 0),
(20, 1, 'El kernel es la parte central del sistema operativo. Controla el acceso a los recursos del hardware y proporciona servicios esenciales a las aplicaciones.', 0),
(21, 1, 'Algunos sistemas de archivos comunes son NTFS (Windows), HFS+ (macOS), ext4 (Linux) y FAT32 (utilizado en dispositivos USB).', 0),
(22, 1, 'es una extensión de la memoria física. El sistema operativo la utiliza para administrar la memoria RAM y el almacenamiento en disco.', 0),
(23, 1, 'Los controladores son programas que permiten que el sistema operativo interactúe con dispositivos de hardware específicos. Son esenciales para el funcionamiento adecuado del sistema.', 0),
(24, 1, 'La concurrencia se refiere a la ejecución simultánea de múltiples procesos. Los sistemas operativos multitarea gestionan la concurrencia mediante planificación de CPU y sincronización.', 0),
(25, 1, 'Los sistemas operativos deben protegerse contra amenazas como virus, malware, ataques de red y vulnerabilidades de software. La seguridad es crucial para mantener la integridad del sistema.', 0),
(26, 1, 'La planificación de CPU determina qué proceso se ejecutará a continuación. Algoritmos como FIFO, SJF, Round Robin y Prioridad se utilizan para tomar estas decisiones.', 0),
(27, 1, 'La paginación es una técnica de administración de memoria utilizada en sistemas operativos. Consiste en dividir la memoria física en bloques de tamaño fijo llamados páginas.', 0),
(28, 1, 'En un sistema monolítico, todas las funciones del sistema operativo. En un sistema basado en microkernel, el núcleo (kernel) contiene solo las funciones esenciales', 0),
(29, 1, 'se refiere a la ejecución simultánea de múltiples tareas en diferentes nodos de la red.', 0),
(30, 1, 'son aquellos que se ejecutan sin interacción directa del usuario. Pueden realizar tareas como actualizaciones automáticas, indexación de archivos o mantenimiento del sistema.', 0);

